issuer: http://127.0.0.1:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: 0.0.0.0:5556

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: localhost:389

    # No TLS for this setup.
    insecureNoSSL: true

    # This would normally be a read-only user.
    bindDN: cn=admin,dc=planetexpress,dc=com
    bindPW: GoodNewsEveryone

    usernamePrompt: Email Address

    userSearch:
      baseDN: ou=People,dc=planetexpress,dc=com
      filter: "(objectClass=inetOrgPerson)"
      username: mail
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: mail
      nameAttr: cn

    groupSearch:
      baseDN: ou=people,dc=planetexpress,dc=com
      filter: "(objectClass=Group)"

      userMatchers:
        # A user is a member of a group when their DN matches
        # the value of a "member" attribute on the group entity.
      - userAttr: DN
        groupAttr: member

      # The group name should be the "cn" value.
      nameAttr: cn

logger:
  level: "debug"

staticClients:
- id: IDAC-APP
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'IDAC-APP'
  secret: K.QY9wP&fcg*5]D
